{
 "title": "Аналитика",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Пользователь нажал \"start\" и запустил бота",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_start_bot_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Пожертвования", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Просмотр пункта меню: Сделать пожертвования",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "user_viewed_donate_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_donate_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Задать вопрос", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Просмотр пункта меню: Задать вопрос",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "user_viewed_question_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_question_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Квиз", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Аналитика по квизу",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_quiz_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр квиза"
    },
    {
     "expr": "user_push_quiz_start_total{job=\"bot_dev\"}",
     "legendFormat": "Запуск игры"
    },
    {
     "expr": "user_viewed_quiz_result_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр результатов квиза"
    }
   ]
  },
  {
   "title": "Результаты игры",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_quiz_result_0_total{job=\"bot_dev\"}",
     "legendFormat": "0"
    },
    {
     "expr": "user_viewed_quiz_result_1_total{job=\"bot_dev\"}",
     "legendFormat": "1"
    },
    {
     "expr": "user_viewed_quiz_result_2_total{job=\"bot_dev\"}",
     "legendFormat": "2"
    },
    {
     "expr": "user_viewed_quiz_result_3_total{job=\"bot_dev\"}",
     "legendFormat": "3"
    },
    {
     "expr": "user_viewed_quiz_result_4_total{job=\"bot_dev\"}",
     "legendFormat": "4"
    },
    {
     "expr": "user_viewed_quiz_result_5_total{job=\"bot_dev\"}",
     "legendFormat": "5"
    },
    {
     "expr": "user_viewed_quiz_result_6_total{job=\"bot_dev\"}",
     "legendFormat": "6"
    },
    {
     "expr": "user_viewed_quiz_result_7_total{job=\"bot_dev\"}",
     "legendFormat": "7"
    },
    {
     "expr": "user_viewed_quiz_result_8_total{job=\"bot_dev\"}",
     "legendFormat": "8"
    },
    {
     "expr": "user_viewed_quiz_result_9_total{job=\"bot_dev\"}",
     "legendFormat": "9"
    },
    {
     "expr": "user_viewed_quiz_result_10_total{job=\"bot_dev\"}",
     "legendFormat": "10"
    }
   ]
  },
  {
   "title": "Аналитика по квизу",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 32 },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Результаты игры",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 32 },
   "targets": [
    { "panelId": 34 }
   ]
  },
  { "title": "Узнать о Федерации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Просмотр пункта меню: Узнать о Федерации",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "user_viewed_federation_values_total{job=\"bot_dev\"}",
     "legendFormat": "Ценности федерации"
    },
    {
     "expr": "user_viewed_federation_activities_total{job=\"bot_dev\"}",
     "legendFormat": "Направления деятельности"
    },
    {
     "expr": "user_viewed_federation_total{job=\"bot_dev\"}",
     "legendFormat": "Узнать о Федерации"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 40 }, "options": { "content": "# Просмотры" } },
  {
   "title": "Узнать о Федерации",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Направления деятельности",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_activities_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ценности федерации",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_values_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Адаптивные виды хоккея", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Просмотр пункта меню: Адаптивные виды хоккея",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "user_viewed_adaptive_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "Адаптивные виды хоккея"
    },
    {
     "expr": "user_viewed_sledzh_hockey_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Следж-хоккей"
    },
    {
     "expr": "user_viewed_special_hockey_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Специальный хоккей"
    },
    {
     "expr": "user_viewed_hockey_for_blind_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Хоккей для незрячих"
    }
   ]
  },
  {
   "title": "Адаптивные виды хоккея",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_adaptive_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Следж хоккей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_sledzh_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Специальный хоккей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_special_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хоккей для незрячих",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_hockey_for_blind_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Кто такой Фырк", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Просмотр пункта меню: Кто такой Фырк",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "user_viewed_who_is_fyrk_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_who_is_fyrk_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Стикерпак", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Просмотр пункта меню: Получить стикерпак",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "user_viewed_sticker_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_sticker_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Всё для хоккея", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Просмотр пункта меню: Всё для хоккея",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "user_viewed_all_for_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_all_for_hockey_total{job=\"bot_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}