repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      # проверяет наличие переноса строки в конце всех текстовых файлов
      - id: end-of-file-fixer
      # предупреждает о добавлении больших файлов в Git
      - id: check-added-large-files
      # предупреждает о сохранении файлов с UTF-8 BOM
      - id: check-byte-order-marker
      # предотвращает сохранение приватных ключей
      - id: detect-private-key
      # проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python
      - id: check-ast
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-return
          - flake8-comprehensions
          - flake8-pie
          - flake8-print
          - flake8-quotes
          - flake8-simplify
          - flake8-variables-names
          - pep8-naming
          - flake8-docstrings
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
