global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "bot_master"
    static_configs:
      - targets: [ 172.17.0.3:8001 ]
  - job_name: "bot_dev"
    static_configs:
      - targets: [ 172.17.0.7:8000 ]
