global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "bot_master"
    static_configs:
      - targets: [ 172.17.0.7:8001 ]
  - job_name: "bot_dev"
    static_configs:
      - targets: [ 172.17.0.8:8000 ]
