{
 "title": "Аналитика",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Пользователь нажал \"start\" и запустил бота",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_start_bot_total{group=\"Owner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Пожертвования", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Пожертвования",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "user_viewed_donate_total{group=\"Donate\"}",
     "legendFormat": "Просмотр"
    },
    {
     "expr": "user_push_donate_total{group=\"Donate\"}",
     "legendFormat": "Переход"
    }
   ]
  },
  {
   "title": "Просмотр пункта меню:  Сделать пожертвования",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_donate_total{group=\"Donate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нажатие кнопки",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_push_donate_total{group=\"Donate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Задать вопрос", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Задать вопрос",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "user_viewed_question_total", "legendFormat": "Просмотр" },
    { "expr": "user_push_question_total", "legendFormat": "Нажатие" }
   ]
  },
  {
   "title": "Нажатия",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_push_question_total{group=\"Question\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Квиз", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Аналитика по квизу",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_quiz_total{group=\"Quiz\"}",
     "legendFormat": "Просмотр квиза"
    },
    {
     "expr": "user_push_quiz_start_total{group=\"Quiz\"}",
     "legendFormat": "Запуск игры"
    },
    {
     "expr": "user_viewed_quiz_result_total{group=\"Quiz\"}",
     "legendFormat": "Просмотр результатов квиза"
    }
   ]
  },
  {
   "title": "Результаты игры",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_quiz_result_0_total{group=\"Quiz\"}",
     "legendFormat": "0"
    },
    {
     "expr": "user_viewed_quiz_result_1_total{group=\"Quiz\"}",
     "legendFormat": "1"
    },
    {
     "expr": "user_viewed_quiz_result_2_total{group=\"Quiz\"}",
     "legendFormat": "2"
    },
    {
     "expr": "user_viewed_quiz_result_3_total{group=\"Quiz\"}",
     "legendFormat": "3"
    },
    {
     "expr": "user_viewed_quiz_result_4_total{group=\"Quiz\"}",
     "legendFormat": "4"
    },
    {
     "expr": "user_viewed_quiz_result_5_total{group=\"Quiz\"}",
     "legendFormat": "5"
    },
    {
     "expr": "user_viewed_quiz_result_6_total{group=\"Quiz\"}",
     "legendFormat": "6"
    },
    {
     "expr": "user_viewed_quiz_result_7_total{group=\"Quiz\"}",
     "legendFormat": "7"
    },
    {
     "expr": "user_viewed_quiz_result_8_total{group=\"Quiz\"}",
     "legendFormat": "8"
    },
    {
     "expr": "user_viewed_quiz_result_9_total{group=\"Quiz\"}",
     "legendFormat": "9"
    },
    {
     "expr": "user_viewed_quiz_result_10_total{group=\"Quiz\"}",
     "legendFormat": "10"
    }
   ]
  },
  { "title": "Узнать о Федерации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Просмотр подпункта меню",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "user_viewed_federation_values_total{group=\"Federation\"}",
     "legendFormat": "Ценности федерации"
    },
    {
     "expr": "user_viewed_federation_activities_total{group=\"Federation\"}",
     "legendFormat": "Направления деятельности"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 38 }, "options": { "content": "# Просмотры" } },
  {
   "title": "Узнать о Федерации",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_total{group=\"Federation\"}",
     "legendFormat": "Просмотр"
    }
   ]
  },
  {
   "title": "Направления деятельности",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_activities_total{group=\"Federation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ценности федерации",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_federation_values_total{group=\"Federation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Адаптивные виды хоккея", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Адаптивные виды хоккея",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "user_viewed_sledzh_hockey_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Следж-хоккей"
    },
    {
     "expr": "user_viewed_special_hockey_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Специальный хоккей"
    },
    {
     "expr": "user_viewed_hockey_for_blind_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "Хоккей для незрячих"
    }
   ]
  },
  {
   "title": "Просмотр",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_viewed_adaptive_hockey_total{group=\"AdaptiveHockey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Кто такой Фырк", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Просмотр",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "user_viewed_who_is_fyrk_total{group=\"WhoIsFyrk\"}",
     "legendFormat": "Просмотр"
    }
   ]
  }
 ]
}